name: CI

on:
    push:
        branches:
            - "!main"
    pull_request:
        types:
            - opened
            - synchronize

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    format:
        name: Format
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Environment setup
              uses: ./.github/workflows/setup

            - name: Check formatting
              run: pnpm format
